/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import entities.Categorie;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.CategorieService;

/**
 *
 * @author ep
 */
public class CategorieForm extends javax.swing.JInternalFrame {
    
        private CategorieService cats;
        private DefaultTableModel model;
        private static int id;
        private boolean test = false;
        

    /**
     * Creates new form CategorieForm
     */
    public CategorieForm() {
        initComponents();
        cats=new CategorieService();
        model=(DefaultTableModel) listeCategories.getModel();
        load();
        
    }
    
    private void load(){
        model.setRowCount(0);
        for(Categorie c:cats.findAll()){
            model.addRow(new Object[]{
                c.getId(),
                c.getCode(),
                c.getLibelle(),
            }
                    );
        }
        test = false;
    }
    

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codetxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        libelletxt = new javax.swing.JTextField();
        ajouterCategorie = new javax.swing.JButton();
        supprimerCategorie = new javax.swing.JButton();
        modifierCategorie = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeCategories = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion des catégories");

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Catégorie", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setText("Code : ");

        jLabel2.setText("libelle : ");

        ajouterCategorie.setText("Ajouter");
        ajouterCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterCategorieActionPerformed(evt);
            }
        });

        supprimerCategorie.setText("Supprimer");
        supprimerCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerCategorieActionPerformed(evt);
            }
        });

        modifierCategorie.setText("Modifier");
        modifierCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierCategorieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(codetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(libelletxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supprimerCategorie, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ajouterCategorie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifierCategorie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(codetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ajouterCategorie)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(modifierCategorie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(supprimerCategorie)
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(libelletxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste des Catégories", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        listeCategories.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "code", "libelle"
            }
        ));
        listeCategories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeCategoriesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listeCategories);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modifierCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierCategorieActionPerformed
        if (test) {
            String code=codetxt.getText();
            String libelle=libelletxt.getText();
            if (code.equals("") | libelle.equals(""))
                JOptionPane.showMessageDialog(this, "Il faut remplir tous les champs ", "WARNING!", JOptionPane.WARNING_MESSAGE);
            else {
                Categorie c=cats.findById(id);
                c.setCode(code);
                c.setLibelle(libelle);
                int reponse=JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment modifier la catégorie");
                if(reponse==0){
                    if(cats.update(c))
                        JOptionPane.showMessageDialog(this, "Catégorie bien modifiée");
                }
            }
            codetxt.setText("");
            libelletxt.setText("");
            load();
        }
    }//GEN-LAST:event_modifierCategorieActionPerformed

    private void ajouterCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterCategorieActionPerformed
        String code=codetxt.getText();
        String libelle=libelletxt.getText();
//        do{
//            JOptionPane.showMessageDialog(this, "Il faut remplir les champs");
//            code=codetxt.getText();
//            libelle=libelletxt.getText();
//        }while (code != "" & libelle != "");
        
        if (code.equals("") | libelle.equals(""))
                JOptionPane.showMessageDialog(this, "Il faut remplir tous les champs ", "WARNING!", JOptionPane.WARNING_MESSAGE);
        
        else if(cats.create(new Categorie(code,libelle))){
            JOptionPane.showMessageDialog(this, "Catgorie bien ajoutée");
            codetxt.setText("");
            libelletxt.setText("");
        }
        load();
    }//GEN-LAST:event_ajouterCategorieActionPerformed

    private void listeCategoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeCategoriesMouseClicked
       test = true;
       id=Integer.parseInt(model.getValueAt(listeCategories.getSelectedRow(), 0).toString());
       codetxt.setText(model.getValueAt(listeCategories.getSelectedRow(), 1).toString());
       libelletxt.setText(model.getValueAt(listeCategories.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_listeCategoriesMouseClicked

    private void supprimerCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerCategorieActionPerformed
       if (test){
            int reponse=JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer la catégorie");
            if(reponse==0){
                 if(cats.delete(cats.findById(id)))
                     JOptionPane.showMessageDialog(this, "catégorie bien supprimée");           
            }
            codetxt.setText("");
            libelletxt.setText("");
            load();
        }
    }//GEN-LAST:event_supprimerCategorieActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterCategorie;
    private javax.swing.JTextField codetxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField libelletxt;
    private javax.swing.JTable listeCategories;
    private javax.swing.JButton modifierCategorie;
    private javax.swing.JButton supprimerCategorie;
    // End of variables declaration//GEN-END:variables
}
