/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import entities.Categorie;
import entities.Chambre;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.CategorieService;
import services.ChambreService;

/**
 *
 * @author NAIFI_Youssef
 */
public class ChambreForm extends javax.swing.JInternalFrame {
    
    private CategorieService cats = new CategorieService();;
    private ChambreService chs = new ChambreService();;
    private DefaultTableModel model;
    private static int id;
    private boolean test = false;

    /**
     * Creates new form ChambreForm
     */
    public ChambreForm() {
        initComponents();
        model = (DefaultTableModel)listeChambres.getModel();
        load();
        loadCategories();
        listeCategories.setSelectedIndex(-1);
    }
    
    private void load() {
        model.setRowCount(0);
        for(Chambre c:chs.findAll()) {
            model.addRow(new Object[]{
            c.getId(),
            c.getTelephone(),
            c.getCategorie()
            }
                );
        }
        test = false;
    }
    
    private void loadCategories() {
        for(Categorie c:cats.findAll()){
            listeCategories.addItem(c);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        teltxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ajouter = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        listeCategories = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeChambres = new javax.swing.JTable();

        setClosable(true);
        setTitle("Gestion des chambres");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nouvelle chambre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setText("Telephone : ");

        jLabel2.setText("Catégorie : ");

        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        listeCategories.setDoubleBuffered(true);
        listeCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeCategoriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(ajouter)
                        .addGap(50, 50, 50)
                        .addComponent(modifier)
                        .addGap(42, 42, 42)
                        .addComponent(supprimer))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(teltxt, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(listeCategories, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(teltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(listeCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouter)
                    .addComponent(supprimer)
                    .addComponent(modifier))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste des chambres", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        listeChambres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "téléphone", "catégorie"
            }
        ));
        listeChambres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeChambresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listeChambres);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        if(test) {
            int reponse=JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer la chambre");
            if(reponse==0){
                if(chs.delete(chs.findById(id)))
                    JOptionPane.showMessageDialog(this, "chambre bien supprimée");
            }
            teltxt.setText("");
            listeCategories.setSelectedIndex(-1);
            load();
        }
    }//GEN-LAST:event_supprimerActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed

        String tel=teltxt.getText();
        Categorie cat = (Categorie) listeCategories.getSelectedItem();
//        do{
//            JOptionPane.showMessageDialog(this, "Il faut remplir les champs");
//            code=codetxt.getText();
//            libelle=libelletxt.getText();
//        }while (code != "" & libelle != "");
        
        if (tel.equals("") | listeCategories.getSelectedIndex() == -1)
                JOptionPane.showMessageDialog(this, "Il faut remplir tous les champs ", "WARNING!", JOptionPane.WARNING_MESSAGE);
        
        else if(chs.create(new Chambre(tel,cat))){
            JOptionPane.showMessageDialog(this, "Catgorie bien ajoutée");
        }
        teltxt.setText("");
        listeCategories.setSelectedIndex(-1);
        load();
    }//GEN-LAST:event_ajouterActionPerformed

    private void listeCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeCategoriesActionPerformed
        
    }//GEN-LAST:event_listeCategoriesActionPerformed

    private void listeChambresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeChambresMouseClicked
        test = true;
        id=Integer.parseInt(model.getValueAt(listeChambres.getSelectedRow(), 0).toString());
        teltxt.setText(model.getValueAt(listeChambres.getSelectedRow(), 1).toString());
        //listeCategories.getModel().setSelectedItem(chs.findById(id).getCategorie());
        listeCategories.getModel().setSelectedItem(model.getValueAt(listeChambres.getSelectedRow(), 2));
    }//GEN-LAST:event_listeChambresMouseClicked

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        if (test) {
            String tel=teltxt.getText();
            Categorie cat = (Categorie) listeCategories.getSelectedItem();
            if (tel.equals(""))
                JOptionPane.showMessageDialog(this, "Il faut remplir le telephone", "WARNING!", JOptionPane.WARNING_MESSAGE);
            else {
                Chambre ch=chs.findById(id);
                ch.setTelephone(tel);
                ch.setCategorie(cat);
                int reponse=JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment modifier la chambre");
                if(reponse==0){
                    if(chs.update(ch))
                        JOptionPane.showMessageDialog(this, "Chambre bien modifiée");
                }
            }
            teltxt.setText("");
            listeCategories.setSelectedIndex(-1);
            load();
        }
    }//GEN-LAST:event_modifierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox listeCategories;
    private javax.swing.JTable listeChambres;
    private javax.swing.JButton modifier;
    private javax.swing.JButton supprimer;
    private javax.swing.JTextField teltxt;
    // End of variables declaration//GEN-END:variables
}
